name: Kanade Build

on:
  push:
    tags: ["v*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Install ALSA dev libraries (amd64 only)
        if: matrix.goarch == 'amd64'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build for linux/${{ matrix.goarch }}
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          OUTPUT_DIR="build/linux_${{ matrix.goarch }}"
          mkdir -p $OUTPUT_DIR
          go build -o $OUTPUT_DIR/kanade-linux-${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kanade-linux-${{ matrix.goarch }}
          path: build/linux_${{ matrix.goarch }}/kanade-linux-${{ matrix.goarch }}

  build-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Build for windows/${{ matrix.goarch }}
        env:
          GOOS: windows
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          OUTPUT_DIR="build/windows_${{ matrix.goarch }}"
          mkdir -p $OUTPUT_DIR
          go build -o $OUTPUT_DIR/kanade-windows-${{ matrix.goarch }}.exe .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kanade-windows-${{ matrix.goarch }}
          path: build/windows_${{ matrix.goarch }}/kanade-windows-${{ matrix.goarch }}.exe

  build-darwin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Build for darwin/${{ matrix.goarch }}
        env:
          GOOS: darwin
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          OUTPUT_DIR="build/darwin_${{ matrix.goarch }}"
          mkdir -p $OUTPUT_DIR
          go build -o $OUTPUT_DIR/kanade-darwin-${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kanade-darwin-${{ matrix.goarch }}
          path: build/darwin_${{ matrix.goarch }}/kanade-darwin-${{ matrix.goarch }}

  release:
    needs: [build-linux, build-windows, build-darwin]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          prerelease: false
          fail_on_unmatched_files: false
          files: artifacts/**/kanade*
